---
version: '3'
services:
  tor-client:
    image: 'nagev/tor'
    deploy:
      restart_policy:
        condition: on-failure

    image: 'clue/polipo'
  polipo:
    image: 'clue/polipo'
    links:
      - tor-client:tor
    command: proxyAddress=0.0.0.0 proxyPort=8181 socksParentProxy=tor:9150
    deploy:
      restart_policy:
        condition: on-failure

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.3.0'
    environment:
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    deploy:
      restart_policy:
        condition: on-failure
  kibana:
    image: 'docker.elastic.co/kibana/kibana:5.3.0'
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    links:
      - elasticsearch

  scrapy:
    build:
      context: ./src/scraper
    environment:
      - http_proxy=http://polipo:8181
      - elasticsearch=http://db:9200
      - https_proxy=http://polipo:8181
      - no_proxy=db
      - urls=https://thehiddenwiki.org/
    links:
      - elasticsearch:db
      - polipo
    deploy:
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
            - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: password
      MYSQL_USER: password
      MYSQL_PASSWORD: password
